"""Tests for parse_transcript — robustness on real and malformed JSONL.

Transcripts are external data (Claude Code writes them); the parser must never
raise on bad input. Adverse cases dominate: malformed lines, empty files,
missing content, noise filtering. Happy path = a couple of clean messages.

Run: py -m pytest tests/test_sessions_indexer.py -v
"""

import json

import pytest

from src.sessions_indexer import parse_transcript


def _write(tmp_path, name, lines):
    """Write a .jsonl from a list of dicts (or raw strings) and return its path."""
    p = tmp_path / name
    out = []
    for line in lines:
        out.append(line if isinstance(line, str) else json.dumps(line))
    p.write_text("\n".join(out), encoding="utf-8")
    return str(p)


def _user(text, **kw):
    d = {"type": "user", "sessionId": "sess-1", "timestamp": "2026-05-20T10:00:00Z",
         "message": {"content": text}}
    d.update(kw)
    return d


def _assistant(text, **kw):
    d = {"type": "assistant", "sessionId": "sess-1", "timestamp": "2026-05-20T10:01:00Z",
         "message": {"content": [{"type": "text", "text": text}]}}
    d.update(kw)
    return d


# ===========================================================================
# HAPPY PATH
# ===========================================================================

def test_parses_user_and_assistant(tmp_path):
    path = _write(tmp_path, "t.jsonl", [
        _user("Comment indexer les transcripts de session efficacement ?"),
        _assistant("On utilise une table FTS5 separee pour les messages."),
    ])
    msgs = parse_transcript(path, "claude-forge")
    assert len(msgs) == 2
    assert msgs[0].role == "user"
    assert msgs[1].role == "assistant"
    assert msgs[0].project == "claude-forge"
    assert msgs[0].session_id == "sess-1"
    assert "transcripts" in msgs[0].content


def test_assistant_text_blocks_joined(tmp_path):
    path = _write(tmp_path, "t.jsonl", [
        {"type": "assistant", "sessionId": "s", "message": {"content": [
            {"type": "text", "text": "Premier bloc de reponse assistant"},
            {"type": "tool_use", "name": "Bash", "input": {}},
            {"type": "text", "text": "deuxieme bloc apres outil"},
        ]}},
    ])
    msgs = parse_transcript(path, "p")
    assert len(msgs) == 1
    assert "Premier bloc" in msgs[0].content
    assert "deuxieme bloc" in msgs[0].content


# ===========================================================================
# NOISE FILTERING — types and blocks that must be dropped
# ===========================================================================

def test_drops_non_user_assistant_types(tmp_path):
    path = _write(tmp_path, "t.jsonl", [
        {"type": "system", "message": {"content": "system stuff here long enough"}},
        {"type": "attachment", "message": {"content": "attachment payload data here"}},
        {"type": "custom-title", "message": {"content": "some title text here long"}},
        _user("vraie question utilisateur conservee ici"),
    ])
    msgs = parse_transcript(path, "p")
    assert len(msgs) == 1
    assert msgs[0].role == "user"


def test_drops_thinking_and_tool_blocks(tmp_path):
    path = _write(tmp_path, "t.jsonl", [
        {"type": "assistant", "sessionId": "s", "message": {"content": [
            {"type": "thinking", "thinking": "reflexion interne tres longue a ignorer"},
            {"type": "tool_use", "name": "Read", "input": {"file": "x"}},
        ]}},
    ])
    msgs = parse_transcript(path, "p")
    assert msgs == []  # no text block → nothing indexable


def test_drops_tool_result_user_messages(tmp_path):
    path = _write(tmp_path, "t.jsonl", [
        {"type": "user", "message": {"content": [
            {"type": "tool_result", "content": "output of a bash command very long"},
        ]}},
    ])
    msgs = parse_transcript(path, "p")
    assert msgs == []


def test_drops_meta_messages(tmp_path):
    path = _write(tmp_path, "t.jsonl", [
        _user("message meta a ignorer completement", isMeta=True),
        _user("vrai message conserve absolument ici"),
    ])
    msgs = parse_transcript(path, "p")
    assert len(msgs) == 1
    assert "vrai message" in msgs[0].content


def test_drops_local_command_echoes(tmp_path):
    path = _write(tmp_path, "t.jsonl", [
        _user("<local-command-caveat>Caveat: generated by user running commands</local-command-caveat>"),
        _user("<command-name>/clear</command-name>"),
        _user("question reelle de raphael conservee"),
    ])
    msgs = parse_transcript(path, "p")
    assert len(msgs) == 1
    assert "question reelle" in msgs[0].content


def test_drops_short_text(tmp_path):
    path = _write(tmp_path, "t.jsonl", [
        _user("ok"),
        _user("oui"),
        _user("message suffisamment long pour etre garde"),
    ])
    msgs = parse_transcript(path, "p")
    assert len(msgs) == 1


# ===========================================================================
# ROBUSTNESS — malformed input must never raise
# ===========================================================================

def test_malformed_json_lines_skipped(tmp_path):
    path = _write(tmp_path, "t.jsonl", [
        "{ this is not valid json",
        "}{",
        _user("ligne valide entre deux lignes corrompues"),
        "null",
        "[1, 2, 3]",  # valid json but not a dict
    ])
    msgs = parse_transcript(path, "p")
    assert len(msgs) == 1
    assert "ligne valide" in msgs[0].content


def test_empty_file(tmp_path):
    path = _write(tmp_path, "t.jsonl", [])
    assert parse_transcript(path, "p") == []


def test_blank_lines_skipped(tmp_path):
    p = tmp_path / "t.jsonl"
    p.write_text("\n\n   \n" + json.dumps(_user("message valide apres lignes vides")) + "\n\n",
                 encoding="utf-8")
    msgs = parse_transcript(str(p), "p")
    assert len(msgs) == 1


def test_message_not_dict(tmp_path):
    path = _write(tmp_path, "t.jsonl", [
        {"type": "user", "message": "string instead of dict here long enough"},
        {"type": "user", "message": None},
        {"type": "user"},  # no message key at all
    ])
    assert parse_transcript(path, "p") == []


def test_content_missing_or_wrong_type(tmp_path):
    path = _write(tmp_path, "t.jsonl", [
        {"type": "user", "message": {"content": None}},
        {"type": "user", "message": {"content": 12345}},
        {"type": "user", "message": {}},
    ])
    assert parse_transcript(path, "p") == []


def test_nonexistent_file_returns_empty(tmp_path):
    assert parse_transcript(str(tmp_path / "nope.jsonl"), "p") == []


def test_fallback_to_agent_id_when_no_session(tmp_path):
    path = _write(tmp_path, "t.jsonl", [
        {"type": "assistant", "agentId": "agent-xyz", "message": {"content": [
            {"type": "text", "text": "reponse d'un sous-agent sans sessionId direct"},
        ]}},
    ])
    msgs = parse_transcript(path, "p")
    assert len(msgs) == 1
    assert msgs[0].session_id == "agent-xyz"


if __name__ == "__main__":
    import sys
    sys.exit(pytest.main([__file__, "-v"]))
